title: Email Archiver
description: Convert EML and MBOX files to a metadata preserving PDF format [EA-PDF](https://pdfa.org/resource/ea-pdf/) using the [Email2Pdf](https://github.com/UIUCLibrary/ea-pdf) tool developed by Tom Habing. 
instructions: 'Attachments are compressed and offered for download at the end of the run. The Add-On also saves metadata about the email as key value pairs on the document.'
type: object
properties:
  email_archive_url:
    title: Email Archive Identifier
    type: string
    description: Unique, permanent, absolute URI identifying the email archive
  url:
    title: URL
    type: string
    format: uri
    description: A publicly accessible Google Drive or Dropbox folder or file. 
  access_level:
    title: Access level for uploaded documents
    type: string
    default: private
    enum:
      - private
      - organization
      - public
  project_id:
    title: Project ID
    type: integer
    description: Project ID of the project you would like to upload the documents to. 
required: 
  - url
  - email_archive_url
categories: 
  - file
version: 2
