title: Email Archiver
description: Test Add-On that uses EaPDF to convert emails to an archived PDF format. 
instructions: ''
type: object
properties:
  name:
    title: Name
    type: string
categories: 
  - file
version: 2
