
name: Run Add-On
on: repository_dispatch

jobs:
  Run-Add-On:
    uses: MuckRock/documentcloud-addon-workflows/.github/workflows/run-addon.yml@v1
    with: 
      runs-on: ubuntu-22.04
      timeout: 360
      apt-packages: openjdk-11-jdk dotnet-sdk-6.0=6.0.423-1 dotnet-runtime-6.0=6.0.31-1
